### ISSUE TITLE
Issue with dependent standalone resource

### ISSUE THREAD

**Issue by salaboy** [java-operator-sdk/java-operator-sdk#1337] opened 2022-07-14 10:41 UTC
## Bug Report

Hi folks, I was trying to create an example using a Standalone dependent resource and for some reason it only works the first time that I create the parent resource. 

#### What did you do?

You can find the source code of the example here: https://github.com/salaboy/from-monolith-to-k8s/blob/main/kubernetes-controllers/java-operator-sdk/conference-controller/src/main/java/com/salaboy/controller/conference/ConferenceReconciler.java

I am curious of someone can spot what the issue is by looking at the code. 
When I create the parent resource for the first time the dependent resource is created and a new deployment is created as result of that. 
If I delete the parent resource, the dependent resource is deleted as expected. But if I create a new resource (with the same name as the first one) the code to reconcile the dependent resource is called, but the deployment is not created. I am 100% sure that I am missing something or I am just hitting a bug. 

#### What did you expect to see?

I've expected a consistent behaviour after creating, deleting and recreating the resource.

#### What did you see instead? Under which circumstances?

inconsistent behavior for the second time that I create the same resource. 

#### Environment

**Kubernetes cluster type:**

GKE

`$ Mention java-operator-sdk version from pom.xml file`

https://github.com/salaboy/from-monolith-to-k8s/blob/main/kubernetes-controllers/java-operator-sdk/conference-controller/pom.xml

`$ java -version`

17

`$ kubectl version`

**Comment by csviri** [comment] 2022-07-14 11:51
Hi @salaboy ,

tried to take a look, I see it requires a service runnig locally, I did not play with that; 

But tried to reproduce it on our sample:

https://github.com/java-operator-sdk/java-operator-sdk/blob/ab111e75836fff5ce828be480e7e17f4d02c2590/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java#L58-L58

and it worked perfectly.

But, please update to newest spring boot starter, since it depends on the latest released sdk version, that has some bug fixes.

If the issues still not resolved, we can also quickly take a look together;

**Comment by salaboy** [comment] 2022-07-15 06:20
@csviri thanks for checking this out.. I was using that example to try to get things working, but yes.. it does work after I restart the operator.. which makes me think about a possible caching issue with the name of the resource. 
If you replace all the URLs in the app for `www.google.com` it should work.. or even if you remove all the service calls, because what I am testing is the dependent resource creation based on a boolean value.

**Comment by salaboy** [comment] 2022-07-15 06:21
Let me try to provide some debug logs.. do you want me to enable debug log for any specific package?

**Comment by salaboy** [comment] 2022-07-15 06:22
I was following the ingress-dependent resource approach: 

https://github.com/java-operator-sdk/java-operator-sdk/blob/ab111e75836fff5ce828be480e7e17f4d02c2590/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java#L61

But I don't want to delete the resource when the flag is false.. I want to only delete when the parent resource is deleted, which is working fine.

**Comment by salaboy** [comment] 2022-07-15 06:23
I was also wondering if this might have something to do with : https://github.com/java-operator-sdk/java-operator-sdk/blob/ab111e75836fff5ce828be480e7e17f4d02c2590/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStatus.java#L5 ?

**Comment by csviri** [comment] 2022-07-15 07:52
> I was following the ingress-dependent resource approach:
> 
> https://github.com/java-operator-sdk/java-operator-sdk/blob/ab111e75836fff5ce828be480e7e17f4d02c2590/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java#L61
> 
> But I don't want to delete the resource when the flag is false.. I want to only delete when the parent resource is deleted, which is working fine.

Yes,for standalone you have to call explicitly delete during reconcile.




> I was also wondering if this might have something to do with :
> 
> https://github.com/java-operator-sdk/java-operator-sdk/blob/ab111e75836fff5ce828be480e7e17f4d02c2590/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStatus.java#L5
> 
> ?

Probably not, rather with informer caches, would be my bet. Unfortunatelly that is quite complex there to support all the features requested.

**Comment by csviri** [comment] 2022-07-15 07:53
> Let me try to provide some debug logs.. do you want me to enable debug log for any specific package?

If just one resource reconciliation that it is fine if you turn on debug level on all java operator sdk, that would help a lot. thx!!

**Comment by csviri** [comment] 2022-07-15 09:45
(Will take a look on this issue ASAP)

**Comment by csviri** [comment] 2022-07-15 10:27
Just as a remark to detect these problems:

We could theoretically check that if there a label selector for the informer, and the resource is created though dependent resource without that label. Will think about that, since this is not easy to miss.

cc @metacosm

**Comment by salaboy** [comment] 2022-07-18 08:29
@csviri thanks for finding the issue and thanks a lot for the pointers.. 
This might also highlight an issue with an example in the projects.. as I was looking at the example referenced in the docs for standalone (with conditional) dependent resources.

**Comment by csviri** [comment] 2022-07-18 12:12
Checking but there it is correctly done so the labels are added for the dependent resources:

https://github.com/java-operator-sdk/java-operator-sdk/blob/0d57629830cdd9ac1c3665438a1493ca438afdc4/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/ServiceDependentResource.java#L27-L27

(Will close this issue, if no objections)

**Closed by csviri** 2022-07-18 12:12 UTC
