### ISSUE TITLE
[V2] Is `resyncPeriod` disalbed in V2 InformerEventSoruce?

### ISSUE THREAD

**Issue by heesuk-ahn** [java-operator-sdk/java-operator-sdk#664] opened 2021-11-09 04:17 UTC
**Question) Is `resyncPeriod` disalbed in V2 InformerEventSoruce?**

https://github.com/java-operator-sdk/java-operator-sdk/blob/0494505de8dcbd14e67ef2a803803b14d9a3ede2/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/InformerEventSource.java#L36-L37

ResyncPeriodMills seems to be disabled as 0 in InformerEventSoruce to be added to v2.

<img width="514" alt="스크린샷 2021-11-09 오후 1 13 49" src="https://user-images.githubusercontent.com/42938941/140860956-687c9085-139d-466b-b5d6-b9ecd0bbb3bb.png">

As shown in the image above, resync triggers the latest state stored in the informer cache at regular intervals.

If this function exists, even if the desired state is not satisfied because dependency resources are deleted by someone, the desired state can be satisfied again due to resync.

In my opinion, if resync is disabled, shouldn't the user have to manually create the EventSource so that it can be restored again when the dependency resource is deleted?

If my thinking is correct, it would be better to handle this in Resync Logic so that we can satisfy the desired state of the Dependency Resource.

**Comment by csviri** [comment] 2021-11-09 10:10
Hi @heesuk-ahn , will take a look again into this more in depth, but checking the implementation of informer before (in fabric8 client), the thinking was the following:

We should always receive the event when it is propagated from the the watch, either its create,update or delete. If you check the implementation of the `processorStore`, on `listWatch` the replace is called from reflector. There is clear that the delete events will be propagated in case the event was missed, since we see the previous object in the store.

So will have to double check, but in terms of consistency it's the same when the resync period is set or not. The event will be eventually propagated to the handler so the controller will be executed.

Note also that there is a constructor where you can provide you informer instance, if you set the resync period there it will propagate the events to the controller.

**Comment by csviri** [comment] 2021-11-09 16:51
@heesuk-ahn I confirmed this with developers of fabric8 client (thank you @shawkins and @manusa ), and it should be as I mentioned before, no events are missed if resync period is 0, resync is mostly there because of compatibility with go-client.
So it's actually correct to have there 0.

Will close the issue for now if no objections, we can re-open it in case there are still questions to clarify.

**Closed by csviri** 2021-11-09 16:51 UTC
