### ISSUE TITLE
SSLHandshakeException :  PKIX path building failed

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#366] opened 2021-03-09 15:35 UTC
I've rebuild the code from master to get rid of the issue fixed by 5cb514de94ea607d5f1cc13c9d515ea7aaf632cf, but now I see the following error when conencting to an OpenShift 4.6.x:

```
2021-03-09 15:56:54,407 ERROR [io.jav.ope.Operator] (Quarkus Main Thread) Error retrieving the server version. Exiting!: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
    at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
    at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
    at io.fabric8.openshift.client.internal.OpenShiftClusterOperationsImpl.fetchVersion(OpenShiftClusterOperationsImpl.java:50)
    at io.fabric8.openshift.client.DefaultOpenShiftClient.getVersion(DefaultOpenShiftClient.java:643)
    at io.javaoperatorsdk.operator.Operator.start(Operator.java:47)
    at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:122)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
    at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
    at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
    at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
    at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
    at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
    at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
    at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
    at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
    at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
    at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
    at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
    at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
    at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
    at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
    at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
    at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
    at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:68)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
    at okhttp3.RealCall.execute(RealCall.java:81)
    at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.handleVersionGet(ClusterOperationsImpl.java:62)
    at io.fabric8.openshift.client.internal.OpenShiftClusterOperationsImpl.fetchOpenshift4Version(OpenShiftClusterOperationsImpl.java:56)
    at io.fabric8.openshift.client.internal.OpenShiftClusterOperationsImpl.fetchVersion(OpenShiftClusterOperationsImpl.java:48)
    ... 14 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
    at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
    at java.base/sun.security.validator.Validator.validate(Validator.java:264)
    at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
    at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
    at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
    ... 57 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
    at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
    at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
    at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
    ... 63 more
```

Some info:

**os:**
```
$ uname -a
Linux mars 5.10.19-200.fc33.x86_64 #1 SMP Fri Feb 26 16:21:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**oc:**
```
Client Version: 4.6.17
Server Version: 4.6.15
Kubernetes Version: v1.19.0+1833054
```

**java:**
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)
```

**dependencies:**
```
  - io.javaoperatorsdk:operator-framework-quarkus-extension:jar:1.7.5-SNAPSHOT:compile
    +- io.javaoperatorsdk:operator-framework-core:jar:1.7.5-SNAPSHOT:compile
    |  +- io.fabric8:openshift-client:jar:5.1.1:compile
    |  |  +- io.fabric8:kubernetes-client:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-core:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-rbac:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-admissionregistration:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-apps:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-autoscaling:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-apiextensions:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-batch:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-certificates:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-coordination:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-discovery:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-events:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-extensions:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-networking:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-metrics:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-policy:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-scheduling:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-storageclass:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-node:jar:5.1.1:compile
    |  |  |  +- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
    |  |  |  |  \- com.squareup.okio:okio:jar:1.17.2:compile
    |  |  |  +- com.squareup.okhttp3:logging-interceptor:jar:3.14.9:compile
    |  |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.12.1:compile
    |  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.1:compile
    |  |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.1:compile
    |  |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.12.1:compile
    |  |  |  +- io.fabric8:zjsonpatch:jar:0.3.0:compile
    |  |  |  \- com.github.mifmif:generex:jar:1.0.2:compile
    |  |  |     \- dk.brics.automaton:automaton:jar:1.11-8:compile
    |  |  +- io.fabric8:openshift-model:jar:5.1.1:compile
    |  |  |  +- io.fabric8:kubernetes-model-common:jar:5.1.1:compile
    |  |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.1:compile
    |  |  +- io.fabric8:openshift-model-operator:jar:5.1.1:compile
    |  |  +- io.fabric8:openshift-model-operatorhub:jar:5.1.1:compile
    |  |  +- io.fabric8:openshift-model-monitoring:jar:5.1.1:compile
    |  |  \- io.fabric8:openshift-model-console:jar:5.1.1:compile
    |  \- org.slf4j:slf4j-api:jar:1.7.30:compile
    +- io.quarkus:quarkus-core:jar:1.12.1.Final:compile
    |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
    |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile
    |  |  +- jakarta.el:jakarta.el-api:jar:3.0.3:compile
    |  |  \- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:compile
    |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile
    |  +- io.quarkus:quarkus-ide-launcher:jar:1.12.1.Final:compile
    |  +- io.quarkus:quarkus-development-mode-spi:jar:1.12.1.Final:compile
    |  +- io.smallrye.config:smallrye-config:jar:1.10.2:compile
    |  |  +- io.smallrye.common:smallrye-common-annotation:jar:1.5.0:compile
    |  |  +- io.smallrye.config:smallrye-config-common:jar:1.10.2:compile
    |  |  |  \- org.eclipse.microprofile.config:microprofile-config-api:jar:1.4:compile
    |  |  +- io.smallrye.common:smallrye-common-expression:jar:1.5.0:compile
    |  |  |  \- io.smallrye.common:smallrye-common-function:jar:1.5.0:compile
    |  |  +- io.smallrye.common:smallrye-common-constraint:jar:1.5.0:compile
    |  |  \- io.smallrye.common:smallrye-common-classloader:jar:1.5.0:compile
    |  +- org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
    |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.6:compile
    |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.0.Final:compile
    |  +- org.jboss.threads:jboss-threads:jar:3.2.0.Final:compile
    |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.1.0.Final:compile
    |  +- org.graalvm.sdk:graal-sdk:jar:21.0.0:compile
    |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile
    |  \- io.quarkus:quarkus-bootstrap-runner:jar:1.12.1.Final:compile
    |     \- io.smallrye.common:smallrye-common-io:jar:1.5.0:compile
    +- io.quarkus.arc:arc:jar:1.12.1.Final:compile
    |  \- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
    +- io.quarkus:quarkus-openshift-client:jar:1.12.1.Final:compile
    |  \- io.quarkus:quarkus-kubernetes-client:jar:1.12.1.Final:compile
    |     +- io.quarkus:quarkus-arc:jar:1.12.1.Final:compile
    |     |  \- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:jar:1.0.1:compile
    |     +- io.quarkus:quarkus-jackson:jar:1.12.1.Final:compile
    |     |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.12.1:compile
    |     |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.12.1:compile
    |     +- org.apache.commons:commons-compress:jar:1.20:compile
    |     +- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile
    |     \- io.smallrye.config:smallrye-config-source-yaml:jar:1.10.2:compile
    |        \- org.yaml:snakeyaml:jar:1.27:compile
    +- io.quarkus:quarkus-kubernetes:jar:1.12.1.Final:compile
    |  \- io.quarkus:quarkus-kubernetes-client-internal:jar:1.12.1.Final:compile
    +- io.quarkus:quarkus-container-image-jib:jar:1.12.1.Final:compile
    \- io.quarkus:quarkus-smallrye-health:jar:1.12.1.Final:compile
       +- io.smallrye:smallrye-health:jar:2.2.6:compile
       |  +- org.eclipse.microprofile.health:microprofile-health-api:jar:2.2:compile
       |  \- io.smallrye:smallrye-health-api:jar:2.2.6:compile
       |     \- io.smallrye.reactive:mutiny:jar:0.13.0:compile
       |        \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
       +- io.smallrye:smallrye-health-provided-checks:jar:2.2.6:compile
       +- io.quarkus:quarkus-vertx-http:jar:1.12.1.Final:compile
       |  +- io.quarkus:quarkus-security-runtime-spi:jar:1.12.1.Final:compile
       |  +- io.quarkus:quarkus-vertx-http-dev-console-runtime-spi:jar:1.12.1.Final:compile
       |  +- io.quarkus.security:quarkus-security:jar:1.1.3.Final:compile
       |  +- io.quarkus:quarkus-vertx-core:jar:1.12.1.Final:compile
       |  |  +- io.quarkus:quarkus-netty:jar:1.12.1.Final:compile
       |  |  |  +- io.netty:netty-codec:jar:4.1.49.Final:compile
       |  |  |  \- io.netty:netty-handler:jar:4.1.49.Final:compile
       |  |  \- io.vertx:vertx-core:jar:3.9.5:compile
       |  |     +- io.netty:netty-common:jar:4.1.49.Final:compile
       |  |     +- io.netty:netty-buffer:jar:4.1.49.Final:compile
       |  |     +- io.netty:netty-transport:jar:4.1.49.Final:compile
       |  |     +- io.netty:netty-handler-proxy:jar:4.1.49.Final:compile
       |  |     |  \- io.netty:netty-codec-socks:jar:4.1.49.Final:compile
       |  |     +- io.netty:netty-codec-http:jar:4.1.49.Final:compile
       |  |     +- io.netty:netty-codec-http2:jar:4.1.49.Final:compile
       |  |     +- io.netty:netty-resolver:jar:4.1.49.Final:compile
       |  |     \- io.netty:netty-resolver-dns:jar:4.1.49.Final:compile
       |  |        \- io.netty:netty-codec-dns:jar:4.1.49.Final:compile
       |  \- io.vertx:vertx-web:jar:3.9.5:compile
       |     +- io.vertx:vertx-web-common:jar:3.9.5:compile
       |     +- io.vertx:vertx-auth-common:jar:3.9.5:compile
       |     \- io.vertx:vertx-bridge-common:jar:3.9.5:compile
       \- io.quarkus:quarkus-jsonp:jar:1.12.1.Final:compile
          \- org.glassfish:jakarta.json:jar:1.1.6:compile
```

**kubeconfig:**
```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://...:6443
  name: ...:6443
```

**code:**
```java
@QuarkusMain
public class Main implements QuarkusApplication {

    @Inject
    Operator operator;

    public static void main(String... args) {
        Quarkus.run(Main.class, args);
    }

    @Override
    public int run(String... args) throws Exception {
        operator.start();

        Quarkus.waitForExit();

        return 0;
    }
}
```

**Comment by lburgazzoli** [comment] 2021-03-09 15:37
Seems similar to https://github.com/quarkusio/quarkus/issues/8947

**Comment by lburgazzoli** [comment] 2021-03-10 05:42
**kubeconfig:**
```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://...:6443
  name: ...:6443
```

**Comment by teszes** [comment] 2021-06-28 11:21
It seems they weren't able to reproduce this at the client level, is this still reproducible on our end?

**Comment by lburgazzoli** [comment] 2021-07-06 05:19
I had no time to check if the it is still happening, will do in the coming days

**Comment by jmrodri** [comment] 2021-08-19 15:15
@lburgazzoli please re-open if this issue still exists. Closing for now as we are not able to reproduce it.

**Closed by jmrodri** 2021-08-19 15:15 UTC
